trigger:
  branches:
    include:
      - latest
  tags:
    include:
      - v*

pool:
  vmImage: windows-latest

steps:
  - script: |
      \@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
      choco install docfx -y
      choco install wkhtmltopdf -y
    displayName: install
  - script: |
      docfx pdf
    displayName: build
  - task: GitHubRelease@0
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    inputs:
      gitHubConnection: aplqo
      repositoryName: '$(Build.Repository.Name)' 
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'auto'
      releaseNotesSource: 'file'
      releaseNotesFile:  ReleaseNote.md
      assets: _pdf/*.pdf
      addChangeLog: true
      compareWith: 'lastFullRelease'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: _pdf/*.pdf
